name: libirmin

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rust:
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 4.13.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-version: ${{ matrix.ocaml-compiler}}

      - run: "opam pin add irmin-tezos.dev git+https://github.com/mirage/irmin.git --no-action"
      - run: "opam install . --deps-only --with-doc --with-test || :"
      - run: opam install irmin-tezos irmin-unix
      - run: opam exec -- make
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cd rust && opam exec -- cargo test -- --test-threads=1

